id: IFF6EA9DC
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T02:10:42+00:00'
last_modified: '2022-06-08T13:31:04.947562+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1PD159451
  title: དུས་རབས ༢༡་པའི་བོད་ལུགས་གསོ་རིག་དངོས་ཚན་སློབ་གསོའི་འཆར་འགོད་སློབ་དེབ། ནད་ཐོག་གི་སྐོར།（བཅོས་སྒྲིག་མ།）
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    AAAA:
      image_group_id: I4PD4562
      title: Volume 1 of dus rabs 21 pa'i bod lugs gso rig dngos tshan slob gso'i
        'char 'god slob deb/ nad thog gi skor/（bcos sgrig ma/）
      total_pages: 216
      order: 1
      base_file: AAAA.txt
    '9433':
      image_group_id: I4PD4563
      title: Volume 2 of dus rabs 21 pa'i bod lugs gso rig dngos tshan slob gso'i
        'char 'god slob deb/ nad thog gi skor/（bcos sgrig ma/）
      total_pages: 150
      order: 2
      base_file: 9433.txt
    548B:
      image_group_id: I4PD4564
      title: Volume 3 of dus rabs 21 pa'i bod lugs gso rig dngos tshan slob gso'i
        'char 'god slob deb/ nad thog gi skor/（bcos sgrig ma/）
      total_pages: 238
      order: 3
      base_file: 548B.txt
    '2799':
      image_group_id: I4PD4565
      title: Volume 4 of dus rabs 21 pa'i bod lugs gso rig dngos tshan slob gso'i
        'char 'god slob deb/ nad thog gi skor/（bcos sgrig ma/）
      total_pages: 212
      order: 4
      base_file: 2799.txt
    527A:
      image_group_id: I4PD4566
      title: Volume 5 of dus rabs 21 pa'i bod lugs gso rig dngos tshan slob gso'i
        'char 'god slob deb/ nad thog gi skor/（bcos sgrig ma/）
      total_pages: 204
      order: 5
      base_file: 527A.txt
    2A4B:
      image_group_id: I4PD4567
      title: Volume 6 of dus rabs 21 pa'i bod lugs gso rig dngos tshan slob gso'i
        'char 'god slob deb/ nad thog gi skor/（bcos sgrig ma/）
      total_pages: 488
      order: 6
      base_file: 2A4B.txt
    3E6B:
      image_group_id: I4PD4568
      title: Volume 7 of dus rabs 21 pa'i bod lugs gso rig dngos tshan slob gso'i
        'char 'god slob deb/ nad thog gi skor/（bcos sgrig ma/）
      total_pages: 302
      order: 7
      base_file: 3E6B.txt
    '8024':
      image_group_id: I4PD4569
      title: Volume 8 of dus rabs 21 pa'i bod lugs gso rig dngos tshan slob gso'i
        'char 'god slob deb/ nad thog gi skor/（bcos sgrig ma/）
      total_pages: 220
      order: 8
      base_file: 8024.txt
    FA24:
      image_group_id: I4PD4570
      title: Volume 9 of dus rabs 21 pa'i bod lugs gso rig dngos tshan slob gso'i
        'char 'god slob deb/ nad thog gi skor/（bcos sgrig ma/）
      total_pages: 184
      order: 9
      base_file: FA24.txt
    '9997':
      image_group_id: I4PD4571
      title: Volume 10 of dus rabs 21 pa'i bod lugs gso rig dngos tshan slob gso'i
        'char 'god slob deb/ nad thog gi skor/（bcos sgrig ma/）
      total_pages: 180
      order: 10
      base_file: 9997.txt
    B1AF:
      image_group_id: I4PD4572
      title: Volume 11 of dus rabs 21 pa'i bod lugs gso rig dngos tshan slob gso'i
        'char 'god slob deb/ nad thog gi skor/（bcos sgrig ma/）
      total_pages: 170
      order: 11
      base_file: B1AF.txt
    '4794':
      image_group_id: I4PD4573
      title: Volume 12 of dus rabs 21 pa'i bod lugs gso rig dngos tshan slob gso'i
        'char 'god slob deb/ nad thog gi skor/（bcos sgrig ma/）
      total_pages: 434
      order: 12
      base_file: 4794.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
