id: opecha:P007037
initial_creation_type: ocr
source_metadata:
  id: bdr:W1PD159451
  title: དུས་རབས ༢༡་པའི་བོད་ལུགས་གསོ་རིག་དངོས་ཚན་སློབ་གསོའི་འཆར་འགོད་སློབ་དེབ། ནད་ཐོག་གི་སྐོར།（བཅོས་སྒྲིག་མ།）
  volume: ''
  author: ''
