id: P007037
initial_creation_type: ocr
source_metadata:
  id: bdr:W1PD159451
  title: དུས་རབས ༢༡་པའི་བོད་ལུགས་གསོ་རིག་དངོས་ཚན་སློབ་གསོའི་འཆར་འགོད་སློབ་དེབ། ནད་ཐོག་གི་སྐོར།（བཅོས་སྒྲིག་མ།）
  author: ''
  volumes:
    e94835a8f1fa42668b902bfe2b2e47d8:
      image_group_id: I4PD4562
      title: ''
      volume_number: 1
      total_pages: 216
    00a90dc3de084e88ad9a7a5c1ecad5bf:
      image_group_id: I4PD4563
      title: ''
      volume_number: 2
      total_pages: 150
    e8eef00a7080488e831970c975e16113:
      image_group_id: I4PD4564
      title: ''
      volume_number: 3
      total_pages: 238
    d7011f5deeb94541b806488f565d3fbc:
      image_group_id: I4PD4565
      title: ''
      volume_number: 4
      total_pages: 212
    7f26063944f4497dad3db3ff8b9ed7a3:
      image_group_id: I4PD4566
      title: ''
      volume_number: 5
      total_pages: 204
    b03928321cad424cba03227db4ecc765:
      image_group_id: I4PD4567
      title: ''
      volume_number: 6
      total_pages: 488
    efaf42bf6ff24ac79ef8085312b28fc0:
      image_group_id: I4PD4568
      title: ''
      volume_number: 7
      total_pages: 302
    9e49c7b25a6d4605b2c9d338c1b0eb3a:
      image_group_id: I4PD4569
      title: ''
      volume_number: 8
      total_pages: 220
    94aab50c6aa6410e906b58723e19e119:
      image_group_id: I4PD4570
      title: ''
      volume_number: 9
      total_pages: 184
    4a982f2a2620420f8b98edf6b63ba698:
      image_group_id: I4PD4571
      title: ''
      volume_number: 10
      total_pages: 180
    dcc98365d0204afdb5c86f7d4ad85aa1:
      image_group_id: I4PD4572
      title: ''
      volume_number: 11
      total_pages: 170
    bdbc25d9c79a4ed18b7ac0232562c81b:
      image_group_id: I4PD4573
      title: ''
      volume_number: 12
      total_pages: 434
ebook_metadata:
  title: དུས་རབས ༢༡་པའི་བོད་ལུགས་གསོ་རིག་དངོས་ཚན་སློབ་གསོའི་འཆར་འགོད་སློབ་དེབ། ནད་ཐོག་གི་སྐོར།（བཅོས་སྒྲིག་མ།）
  author: ''
  sku: P007037
  cover: cover.jpg
  layers:
  - pagination
